const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS'
const GET_FEED_FAILURE = 'GET_FEED_FAILURE'
const GET_FEED_LOADING = 'GET_FEED_LOADING'

export const GetFeedTypes = {
  GET_FEED_SUCCESS,
  GET_FEED_FAILURE,
  GET_FEED_LOADING,
}
